root: true
env:
  browser: true
  es2020: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
  - react
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
